### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by marcosTaron** [marcosTaron/movie-it-chalenge#1]
**Back-end**
- [x] You can use local storage to store/retrieve the data or a database, it’s up to you. **using mongo db**
- [x] There should be some level of automated testing implemented (Unit, integration).
- [x] There should be seed data to start the project
- [x] The movie data should contain at least the following: title, genre, release date, main actors, summarized plot, youtube trailer.

**Front-end**
- [x] There should be navigation, a custom UI (you may use bootstrap, semanticUI or any
other CSS library/framework). **prob using styled components and routes**
- [ ] There should be some level of automated testing implemented (Unit, end-2-end).
- [x] The other details of the application are up to you.

**Bonus point**
- [ ] When creating a movie, allow the user to search for a film title and retrieve results
from the OMDB API (http://www.omdbapi.com/), filling the movie info from the data
retrieved from the API.
- [x] A simple authentication mechanism (with hardcoded users) for accessing the
create/edit pages.
